---
title: "ProbitRegression_Stat"
author: "Hailie Dono"
date: "2023-12-10"
output: html_document
---
## Probit Regression

Loading any necessary packages...
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Generating some data to use...
```{r}
# Set seed
set.seed(123)

# Number of observations
n <- 200

# Generate predictor variables
x1 <- rnorm(n)
x2 <- rnorm(n)
x3 <- rnorm(n)

# Generate binary outcome variable
true_coefficients <- c(0.5, -0.8, 0.3)
linear_predictor <- true_coefficients[1] + true_coefficients[2] * x1 + true_coefficients[3] * x2
probabilities <- pnorm(linear_predictor)
y <- rbinom(n, 1, probabilities)

# Create a dataframe with the variables
practice_data <- data.frame(y, x1, x2, x3)

# Check the first few rows of the dataset
head(practice_data)

# Checking what glm() gives us
# summary(check <- glm(y ~ x1 + x2 + x3, data = practice_data, family = binomial(link = 'probit')))

```


Our Function
```{r}
Probit_Regression <- function(X, y) {
# Our function to get probabilities
probitLL = function(beta, X, y){
  mu = X %*% beta
  ll = sum(y * pnorm(mu, log = T) + (1 - y) * log(1 - pnorm(mu)))
  -ll
}
# Initial betas
init = rep(0, ncol(X))
# Let's do optimization!
optimResult = optim(
  fn  = probitLL,
  par = init,
  X = X,
  y = y,
  method  = "BFGS",
  control = list(maxit = 5000, reltol = 1e-12),
  hessian = TRUE
)

#optimResult

# results
B  = optimResult$par
se = sqrt(diag(solve((optimResult$hessian))))
Z  = B/se
p  = pnorm(abs(Z), lower = FALSE)*2
# Our function output
print(round(data.frame(B, se, Z, p), 4))
}


# Preparing data we generated to go in our probit regression
X = model.matrix(y ~ x1 + x2 + x3,practice_data)
Y = practice_data$y

# Compare output of our function
Probit_Regression(X,Y)

# glm output
summary(check <- glm(y ~ x1 + x2 + x3, data = practice_data, family = binomial(link = 'probit')))

```

