---
title: "ZIP Regression"
author: "Hailie Dono"
date: "2023-12-19"
output: html_document
---


## Zero-Inflated Poisson Regression

Loading any necessary packages...
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
library(pscl)  # We Poisson regression in R using the glm function in one of the core packages... However, we need another package to run the zero-inflated Poisson model. We use the pscl package.
```


Pulling up some count data...
```{r}
# Using data on 250 groups that went to a park. Each group was questioned about how many fish they caught (count), how many children were in the group (child), how many people were in the group (persons), and whether or not they brought a camper to the park (camper)
# From UCLA's Statistical Methods and Data Analytics website
zinb <- read.csv("https://stats.idre.ucla.edu/stat/data/fish.csv")
zinb <- within(zinb, {
    nofish <- factor(nofish)
    livebait <- factor(livebait)
    camper <- factor(camper)
})

## Citation: 
#ZERO-INFLATED POISSON REGRESSION | R DATA ANALYSIS EXAMPLES. 
#https://stats.oarc.ucla.edu/r/dae/zip/
#(accessed December 18, 2021).


# Checking 
summary(m1 <- zeroinfl(count ~ persons + livebait, data = zinb) )
```

Our Function
```{r}
ZIP_Regression <- function(X, y) {
  zip_ll <- function(y, X, beta){
    # Extract parameters
     logitpars = beta[1:3]  
     poispars  = beta[4:6]
 
    # Logit part;
     LPlogit = X %*% logitpars
     logi0   = plogis(LPlogit)  # alternative 1/(1+exp(-LPlogit))
  
    # Poisson part
     mupois = exp(X %*% poispars)
  
    # LLs
     logliklogit = log( logi0 + exp(log(1 - logi0) - mupois) )
     loglikpois  = log(1 - logi0) + dpois(y, lambda = mupois, log = TRUE)
  
    y0 = y == 0  # 0 values
    yc = y > 0   # Count part
  
    ll = sum(logliklogit[y0]) + sum(loglikpois[yc])
   -ll
   }
    
  #Initial params
  starts = c(rep(0, 3), rep(0, 3))
  
  # Let's optimize!
  OptimResult = optim(
  par = starts ,
  fn  = zip_ll,
  X = X,
  y = y, 
  method  = "BFGS",
  control = list(maxit = 5000, reltol = 1e-12),
  hessian = TRUE)
  
  # Getting our results
  B <- OptimResult$par
  hessian <- OptimResult$hessian
  cholesky <- chol(hessian)
  cholesky_inv <- chol2inv(cholesky)
  se <- sqrt(diag(cholesky_inv))
  Z  = B/se
  p  = pnorm(abs(Z), lower = FALSE)*2
  # Our function output
  print("Zero-inflation model coefficients (binomial with logit link):")
  print(round(data.frame(B[1:3], se[1:3], Z[1:3], p[1:3]), 4))
  
  print("Count model coefficients (poisson with log link):")
  print(round(data.frame(B[4:6], se[4:6], Z[4:6], p[4:6]), 4))
}


# Preparing data we generated to go in our poisson regression
x = model.matrix(count ~ persons + livebait, zinb)
y = zinb$count

# Compare output of our function
ZIP_Regression(x,y)

```

